<#
.SYNOPSIS
    Build the multi-assembler distribution of x16lib.

    Assembles the whole library into a binary blob at a fixed address
    (dist\x16lib.bin, org $8000) with ACME -- the single, tested source
    of truth -- then generates binding include files for ACME, ca65,
    64tass and KickAssembler from that build's symbol list, so the blob
    and the bindings can never drift apart.

.EXAMPLE
    .\dist.ps1                    # build blob + bindings, run the smoke test
    .\dist.ps1 -SkipEmuTest       # no emulator run (CI without the emulator)
    .\dist.ps1 -Ca65 ca65.exe -Tass 64tass.exe -KickJar KickAss.jar
                                  # also assemble the dist examples with the
                                  # real assemblers as a syntax check
#>
param(
    [switch]$SkipEmuTest,
    [string]$Ca65,
    [string]$Tass,
    [string]$KickJar
)

$ErrorActionPreference = "Stop"

function Fail([string]$message) {
    Write-Host $message -ForegroundColor Red
    exit 1
}

$root = $PSScriptRoot
$acme = Join-Path $root "acme\acme.exe"
$src  = Join-Path $root "src"
$dist = Join-Path $root "dist"
$build = Join-Path $root "build"

if (-not (Test-Path $acme)) { Fail "missing: $acme" }
if (-not (Test-Path $build)) { New-Item -ItemType Directory -Path $build | Out-Null }

# --- 1. assemble the blob ---------------------------------------------
$bin = Join-Path $dist "x16lib.bin"
$prg = Join-Path $dist "X16LIB.PRG"
$sym = Join-Path $build "x16lib_blob.sym"

Write-Host "acme  dist\x16lib_blob.asm -> dist\x16lib.bin"
& $acme -I $src -f plain -o $bin -l $sym (Join-Path $dist "x16lib_blob.asm")
if ($LASTEXITCODE -ne 0) { Fail "blob assembly failed" }
& $acme -I $src -f cbm -o $prg (Join-Path $dist "x16lib_blob.asm")
if ($LASTEXITCODE -ne 0) { Fail "blob PRG assembly failed" }

$blobSize = (Get-Item $bin).Length
$org = 0x6800
Write-Host ('      {0} bytes, ${1:X4}-${2:X4}' -f $blobSize, $org, ($org + $blobSize - 1))

# --- 2. parse the symbol list -----------------------------------------
# ACME emits one line per global symbol:  \tname\t= $hex\t; comment
# Zone-local (.name) and cheap-local (@name) symbols never appear here.
$symbols = @{}
foreach ($line in Get-Content $sym) {
    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\$([0-9A-Fa-f]+)') {
        $name = $Matches[1]
        $value = [Convert]::ToInt64($Matches[2], 16)
        # Skip ACME-side plumbing that means nothing to another assembler:
        # module gates, include guards, and the macro-definition marker.
        if ($name -match '^(X16_USE_|X16_CONST_|X16_MACROS$)') { continue }
        $symbols[$name] = $value
    }
}
if ($symbols.Count -lt 400) { Fail "symbol list looks truncated: $($symbols.Count) symbols" }
Write-Host "      $($symbols.Count) symbols exported"

$names = $symbols.Keys | Sort-Object
$stamp = "x16lib bindings -- GENERATED by dist.ps1, do not edit." + [Environment]::NewLine +
         ("blob: x16lib.bin, $blobSize bytes at `${0:X4} (X16LIB.PRG = the same with a load header)." -f $org) + [Environment]::NewLine +
         "The X16LIB_ORG symbol below carries the org; place the binary exactly there." + [Environment]::NewLine +
         "Only use this file with the x16lib.bin produced by the same dist build."

function Write-Binding([string]$dir, [string]$comment, [string]$header,
                      [scriptblock]$line, [string]$template, [string]$footer) {
    $outDir = Join-Path $dist $dir
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
    $out = New-Object System.Text.StringBuilder
    foreach ($l in $stamp -split [Environment]::NewLine) {
        [void]$out.AppendLine("$comment $l")
    }
    [void]$out.AppendLine($header)
    foreach ($n in $names) {
        [void]$out.AppendLine((& $line $n $symbols[$n]))
    }
    if ($template) {
        [void]$out.AppendLine()
        [void]$out.Append((Get-Content (Join-Path $dist "templates\$template") -Raw))
    }
    if ($footer) { [void]$out.AppendLine($footer) }
    $path = Join-Path $outDir "x16lib.inc"
    [IO.File]::WriteAllText($path, $out.ToString())
    Write-Host "      -> dist\$dir\x16lib.inc"
}

# --- 3. emit the four binding files ------------------------------------
Write-Binding "acme" ";" "!ifdef X16LIB_INC !eof`r`nX16LIB_INC = 1" `
    { param($n, $v) "{0} = `${1:X}" -f $n, $v } `
    "" ""

Write-Binding "ca65" ";" ".ifndef X16LIB_INC`r`nX16LIB_INC = 1" `
    { param($n, $v) "{0} = `${1:X}" -f $n, $v } `
    "ca65-macros.inc" "`r`n.endif"

Write-Binding "64tass" ";" "" `
    { param($n, $v) "{0} = `${1:X}" -f $n, $v } `
    "64tass-macros.inc" ""

Write-Binding "kickass" "//" "" `
    { param($n, $v) ".const {0} = `${1:X}" -f $n, $v } `
    "kickass-macros.inc" ""

# --- 4. smoke-test the blob + bindings on the emulator ------------------
if (-not $SkipEmuTest) {
    Write-Host "smoke: test\blobsmoke.asm against the generated ACME bindings"
    & powershell -ExecutionPolicy Bypass -File (Join-Path $root "build.ps1") -Test -Source "test\blobsmoke.asm"
    if ($LASTEXITCODE -ne 0) { Fail "blob smoke test failed" }
}

# --- 5. optionally syntax-check with the real assemblers ----------------
# Each example is assembled to a PRG in build\; failures fail the dist.
function Find-Tool([string]$given, [string]$name) {
    if ($given) { if (Test-Path $given) { return $given } else { Fail "not found: $given" } }
    $c = Get-Command $name -ErrorAction SilentlyContinue
    if ($c) { return $c.Source }
    return $null
}

$ca65Exe = Find-Tool $Ca65 "ca65"
$tassExe = Find-Tool $Tass "64tass"
$kickJarPath = $KickJar

if ($ca65Exe) {
    $ld65 = Join-Path (Split-Path $ca65Exe) "ld65.exe"
    Write-Host "ca65  dist\examples\hello-ca65.s"
    & $ca65Exe --cpu 65C02 -I (Join-Path $dist "ca65") --bin-include-dir $dist -o (Join-Path $build "hello-ca65.o") (Join-Path $dist "examples\hello-ca65.s")
    if ($LASTEXITCODE -ne 0) { Fail "ca65 assembly failed" }
    & $ld65 -C (Join-Path $dist "ca65\x16lib.cfg") -o (Join-Path $build "HELLO-CA65.PRG") (Join-Path $build "hello-ca65.o")
    if ($LASTEXITCODE -ne 0) { Fail "ld65 link failed" }
    Write-Host ("      -> build\HELLO-CA65.PRG, {0} bytes" -f (Get-Item (Join-Path $build "HELLO-CA65.PRG")).Length)
} else { Write-Host "ca65 not found -- skipping the ca65 example" -ForegroundColor Yellow }

if ($tassExe) {
    Write-Host "64tass dist\examples\hello-64tass.asm"
    & $tassExe -C -a --cbm-prg -o (Join-Path $build "HELLO-64TASS.PRG") (Join-Path $dist "examples\hello-64tass.asm") -I $dist
    if ($LASTEXITCODE -ne 0) { Fail "64tass assembly failed" }
    Write-Host ("      -> build\HELLO-64TASS.PRG, {0} bytes" -f (Get-Item (Join-Path $build "HELLO-64TASS.PRG")).Length)
} else { Write-Host "64tass not found -- skipping the 64tass example" -ForegroundColor Yellow }

if ($kickJarPath -and (Test-Path $kickJarPath)) {
    Write-Host "kickass dist\examples\hello-kickass.asm"
    & java -jar $kickJarPath (Join-Path $dist "examples\hello-kickass.asm") -o (Join-Path $build "HELLO-KICKASS.PRG")
    if ($LASTEXITCODE -ne 0) { Fail "KickAssembler assembly failed" }
    # KickAss drops a .sym next to its output dir unasked; keep dist clean
    Remove-Item (Join-Path $dist "examples\hello-kickass.sym") -Force -ErrorAction SilentlyContinue
    Write-Host ("      -> build\HELLO-KICKASS.PRG, {0} bytes" -f (Get-Item (Join-Path $build "HELLO-KICKASS.PRG")).Length)
} else { Write-Host "KickAss.jar not given -- skipping the KickAssembler example" -ForegroundColor Yellow }

Write-Host "dist complete" -ForegroundColor Green
